boot.o: boot.S multiboot.h x86_desc.h types.h
execute.o: execute.S
linkage.o: linkage.S
x86_desc.o: x86_desc.S x86_desc.h types.h
execute.o: execute.c execute.h lib.h types.h paging.h x86_desc.h pcb.h
filesystem.o: filesystem.c filesystem.h lib.h types.h pcb.h
i8259.o: i8259.c i8259.h types.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h filesystem.h keyboard.h rtc.h paging.h terminal.h
keyboard.o: keyboard.c keyboard.h i8259.h types.h lib.h
lib.o: lib.c lib.h types.h terminal.h keyboard.h i8259.h
paging.o: paging.c paging.h x86_desc.h types.h lib.h
rtc.o: rtc.c rtc.h lib.h types.h i8259.h
setup_idt.o: setup_idt.c x86_desc.h types.h lib.h linkage.h \
  system_calls.h execute.h paging.h filesystem.h rtc.h terminal.h \
  keyboard.h i8259.h
system_calls.o: system_calls.c system_calls.h lib.h types.h execute.h \
  paging.h x86_desc.h filesystem.h rtc.h terminal.h keyboard.h i8259.h \
  pcb.h
terminal.o: terminal.c terminal.h keyboard.h i8259.h types.h lib.h
tests.o: tests.c tests.h filesystem.h lib.h types.h x86_desc.h rtc.h \
  terminal.h keyboard.h i8259.h
