boot.o: boot.S multiboot.h x86_desc.h types.h
execute_asm.o: execute_asm.S
linkage.o: linkage.S
x86_desc.o: x86_desc.S x86_desc.h types.h
execute.o: execute.c paging.h x86_desc.h types.h lib.h i8259.h \
  system_calls.h shared_global_variables.h execute.h filesystem.h
filesystem.o: filesystem.c filesystem.h lib.h types.h \
  shared_global_variables.h
i8259.o: i8259.c i8259.h types.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h filesystem.h shared_global_variables.h keyboard.h rtc.h \
  paging.h terminal.h system_calls.h pit.h
keyboard.o: keyboard.c keyboard.h i8259.h types.h lib.h pit.h \
  shared_global_variables.h paging.h x86_desc.h system_calls.h execute.h \
  terminal.h
lib.o: lib.c lib.h types.h terminal.h keyboard.h i8259.h \
  shared_global_variables.h paging.h x86_desc.h execute.h
paging.o: paging.c paging.h x86_desc.h types.h lib.h i8259.h
pit.o: pit.c pit.h i8259.h types.h lib.h shared_global_variables.h \
  linkage.h system_calls.h execute.h paging.h x86_desc.h keyboard.h
rtc.o: rtc.c rtc.h lib.h types.h i8259.h
setup_idt.o: setup_idt.c x86_desc.h types.h lib.h linkage.h \
  system_calls.h shared_global_variables.h
system_calls.o: system_calls.c execute.h lib.h types.h \
  shared_global_variables.h filesystem.h rtc.h terminal.h keyboard.h \
  i8259.h system_calls.h paging.h x86_desc.h
terminal.o: terminal.c terminal.h keyboard.h i8259.h types.h lib.h \
  shared_global_variables.h paging.h x86_desc.h execute.h
tests.o: tests.c tests.h filesystem.h lib.h types.h \
  shared_global_variables.h x86_desc.h rtc.h terminal.h keyboard.h \
  i8259.h
